version: '3.7'
services:
    nginx:
      image: nginx:alpine
      container_name: nginx
      volumes: 
      - type: bind
        source: ./nginx/nginx.conf
        target: /etc/nginx/nginx.conf
      ports:
      - target: 80
        published: 80
      depends_on:
      - flask-app
    flask-app:
      build: ./flask-app
      container_name: flask-app
      ports:
      - target: 5000
        published: 5000
      environment:
        MYSQL_USER: ${MYSQL_USER}
        MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      depends_on:
      - database
    database:
      build: ./db
      container_name: mysql
      ports:
      - target: 3306
        published: 3306
      environment:
        MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
        MYSQL_DATABASE: flask-db
