#Use Python Image
FROM python:latest

# Install apt dependencies
RUN sudo apt update
# Copy contents into image
Copy . .
# run pip dependencies
RUN pip3 install 
# Expose correct port
EXPOSE 5000
# Create an entrypoint

